on:
  push:
    tags:
      - v*

name: Test, build, publish
jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Update
        run: |
          npm install
          npm update-list
        env:
          GITHUB_ACTION: true

      - name: Test
        run: |
          npm test
        env:
          GITHUB_ACTION: true

      - name: Build and publish
        run: |
          npm run build
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
          npm publish --access public
